/*
 * Copyright (C) 2026 OpenPnP contributors
 */
package org.openpnp.machine.reference.camera;

import java.awt.image.BufferedImage;
import java.util.concurrent.atomic.AtomicLong;

import org.openpnp.spi.TriggeredCamera;
import org.simpleframework.xml.Root;

/**
 * Bottom-looking-up simulation camera with deterministic external-trigger semantics.
 *
 * The rendered image comes from SimulatedUpCamera, so the nozzle and held part are generated by the
 * existing OpenPnP simulation model. Fly-By logic therefore sees the same TriggeredCamera contract
 * as it will with a real GenICam / USB3 Vision camera.
 */
@Root
public class FlyBySimulatedUpCamera extends SimulatedUpCamera implements TriggeredCamera {
    private final AtomicLong triggerSequence = new AtomicLong();
    private volatile TriggerMode triggerMode = TriggerMode.Live;

    @Override
    public void setTriggerMode(TriggerMode mode) throws Exception {
        if (mode == null) {
            throw new IllegalArgumentException("mode must not be null");
        }
        triggerMode = mode;
    }

    @Override
    public TriggerMode getTriggerMode() {
        return triggerMode;
    }

    @Override
    public long getLastTriggerSequence() {
        return triggerSequence.get();
    }

    @Override
    public TriggeredFrame captureTriggered(long timeoutMilliseconds) throws Exception {
        if (triggerMode != TriggerMode.External) {
            throw new IllegalStateException("Fly-By simulation camera is not in external trigger mode.");
        }
        if (timeoutMilliseconds <= 0) {
            throw new IllegalArgumentException("timeoutMilliseconds must be positive");
        }

        BufferedImage image = internalCapture();
        if (image == null) {
            throw new IllegalStateException("Fly-By simulation camera did not produce an image.");
        }

        long sequence = triggerSequence.incrementAndGet();
        return new TriggeredFrame(image, sequence, System.nanoTime());
    }
}
